Adds verify-helm-docs.sh and update-helm-docs.sh scripts. Verify helm-docs during lint
cert-manager/trust pull request #24
Opened 2022-05-03 10:14 UTC by JoshVanL

/assign @SgtCoDFish 

This PR adds a scripts, run at `make lint`, which verifies that the helm chart `README.md` file is kept up to date.

An update script is also added which will update the helm chart `README.md`.

2022-05-04 15:24 UTC, SgtCoDFish requested changes
I have a suggestion on how we're installing this tool, but I really like the idea of this PR and I think we should definitely have something like this in `cert-manager/trust`!

2022-05-04 15:24 UTC, SgtCoDFish commented on Makefile
> +
nit (non-blocking): Could we use `make verify-helm-docs` here? I think it'd be a little clearer that it's a verification step and that nothing is built from that make target.

2022-05-13 18:04 UTC, JoshVanL commented on go.mod
> +	github.com/norwoodj/helm-docs v1.9.1
[helm-docs](https://github.com/norwoodj/helm-docs/releases) doesn't provide all of the target arches.

To resolve this I have added a separate `go.mod` for `hack/bin` so is no longer vendred at the top level.

Makefile binary deps are now built from that bin directory to use that `go.mod`

2022-05-13 18:10 UTC, JoshVanL commented
Moved to https://github.com/cert-manager/trust/pull/28

/close

2022-05-13 18:10 UTC, closed without merging