Fix copy paste errors, add warning to readme
cert-manager/trust pull request #45
Opened 2022-08-01 15:42 UTC by SgtCoDFish

See individual commit messages for more context!

2022-08-01 16:04 UTC, JoshVanL requested changes
One thing

/assign @SgtCoDFish

2022-08-01 16:04 UTC, JoshVanL commented on hack/tools/go.mod
> +module github.com/cert-manager/csi-driver/hack/tools
```suggestion
module github.com/cert-manager/trust/hack/tools
```

2022-08-01 16:09 UTC, SgtCoDFish commented on hack/tools/go.mod
> +module github.com/cert-manager/csi-driver/hack/tools
Ah good spot, cheers! Fixed now :grin:

2022-08-02 09:04 UTC, JoshVanL commented
/lgtm

2022-08-02 09:04 UTC, merged